from typing import Dict, Set
from app.identity.models import UserRole

# Core Permission Constants
PERM_PLATFORM_MANAGE = "platform:manage"
PERM_TENANT_MANAGE = "tenant:manage"
PERM_TENANT_USERS_MANAGE = "tenant:users:manage"
PERM_SEARCH_EXECUTE = "search:execute"
PERM_INVESTIGATION_CREATE = "investigation:create"
PERM_INVESTIGATION_READ = "investigation:read"
PERM_INVESTIGATION_UPDATE = "investigation:update"
PERM_EVIDENCE_MANAGE = "evidence:manage"
PERM_AUDIT_READ = "audit:read"
PERM_NEWS_SEARCH = "news:search"
PERM_NEWS_INVESTIGATE = "news:investigate"

ROLE_PERMISSIONS: Dict[UserRole, Set[str]] = {
    UserRole.SUPER_ADMIN: {
        PERM_PLATFORM_MANAGE,
        PERM_TENANT_MANAGE,
        PERM_TENANT_USERS_MANAGE,
        PERM_SEARCH_EXECUTE,
        PERM_INVESTIGATION_CREATE,
        PERM_INVESTIGATION_READ,
        PERM_INVESTIGATION_UPDATE,
        PERM_EVIDENCE_MANAGE,
        PERM_AUDIT_READ,
        PERM_NEWS_SEARCH,
        PERM_NEWS_INVESTIGATE,
    },
    UserRole.TENANT_ADMIN: {
        PERM_TENANT_USERS_MANAGE,
        PERM_SEARCH_EXECUTE,
        PERM_INVESTIGATION_CREATE,
        PERM_INVESTIGATION_READ,
        PERM_INVESTIGATION_UPDATE,
        PERM_EVIDENCE_MANAGE,
        PERM_AUDIT_READ,
        PERM_NEWS_SEARCH,
        PERM_NEWS_INVESTIGATE,
    },
    UserRole.ANALYST: {
        PERM_SEARCH_EXECUTE,
        PERM_INVESTIGATION_CREATE,
        PERM_INVESTIGATION_READ,
        PERM_INVESTIGATION_UPDATE,
        PERM_EVIDENCE_MANAGE,
        PERM_NEWS_SEARCH,
        PERM_NEWS_INVESTIGATE,
    },
    UserRole.INVESTIGATOR: {
        PERM_SEARCH_EXECUTE,
        PERM_INVESTIGATION_CREATE,
        PERM_INVESTIGATION_READ,
        PERM_INVESTIGATION_UPDATE,
        PERM_EVIDENCE_MANAGE,
        PERM_NEWS_SEARCH,
        PERM_NEWS_INVESTIGATE,
    },
    UserRole.USER: {
        PERM_SEARCH_EXECUTE,
        PERM_INVESTIGATION_READ,
    },
}

