import uuid
from typing import List, Optional, Dict, Any
from datetime import datetime
from app.reports.models import ReportRecord, GenerateReportRequest
from app.findings.service import finding_service
from app.evidence.service import evidence_service
from app.investigations.service import investigation_service
from app.infrastructure.mongodb.repositories import report_repo

class ReportService:
    def __init__(self):
        # tenant_id -> Dict[report_id, ReportRecord]
        self._memory_store: Dict[str, Dict[str, ReportRecord]] = {}

    def _get_tenant_store(self, tenant_id: str) -> Dict[str, ReportRecord]:
        if tenant_id not in self._memory_store:
            self._memory_store[tenant_id] = {}
        return self._memory_store[tenant_id]

    def generate_report(self, tenant_id: str, author_name: str, req: GenerateReportRequest) -> ReportRecord:
        report_id = f"rep_{uuid.uuid4().hex[:12]}"
        now = datetime.utcnow().isoformat()
        
        # Pull associated investigation, findings, and evidence
        inv = investigation_service.get_investigation(tenant_id, req.investigation_id)
        target = inv.target if inv else "Target Identifier"
        target_type = inv.target_type if inv else "DOMAIN"
        inv_title = inv.title if inv else req.title

        # Generate markdown content
        findings_md = ""
        findings = finding_service.list_findings(tenant_id, investigation_id=req.investigation_id)
        if findings:
            for i, f in enumerate(findings):
                findings_md += f"### 2.{i+1} {f.title}\n- **Severity**: {f.severity}\n- **Confidence**: {f.confidence}%\n- **Description**: {f.description}\n- **Remediation**: {f.mitigation or 'N/A'}\n\n"
        else:
            findings_md = "_No security findings attached to this dossier._\n\n"

        evidence_md = ""
        evidence_items = evidence_service.list_evidence(tenant_id, investigation_id=req.investigation_id)
        if evidence_items:
            for ev in evidence_items:
                evidence_md += f"- **{ev.source}** [{ev.provider}]\n  - SHA-256 Digest: `{ev.hash}`\n  - Timestamp: {ev.timestamp}\n"
        else:
            evidence_md = "_No cryptographic evidence records attached._\n"

        markdown_doc = f"""# SENTIAL INTELLIGENCE DOSSIER
**CLASSIFICATION**: {req.classification}  
**DOSSIER ID**: {report_id}  
**CASE FILE**: {inv_title} ({req.investigation_id})  
**PRIMARY TARGET**: {target} ({target_type})  
**PREPARED BY**: {author_name}  
**DATE GENERATED**: {now}  

---

## 1. EXECUTIVE SUMMARY
{req.executive_summary}

---

## 2. CORRELATED THREAT FINDINGS
{findings_md}
---

## 3. EVIDENCE CUSTODY & PROVENANCE (SHA-256)
{evidence_md}
---
*Generated by Sential Modular Intelligence & Investigation SaaS Platform*
"""

        record = ReportRecord(
            id=report_id,
            tenant_id=tenant_id,
            investigation_id=req.investigation_id,
            title=req.title,
            type=req.type,
            status="READY",
            author=author_name,
            created_at=now,
            executive_summary=req.executive_summary,
            classification=req.classification,
            finding_ids=req.finding_ids,
            evidence_citations=req.evidence_citations,
            entity_ids=req.entity_ids,
            markdown_content=markdown_doc
        )

        r_dict = record.dict()
        store = self._get_tenant_store(tenant_id)
        store[report_id] = record
        report_repo._sync_write({"id": report_id, "tenant_id": tenant_id}, r_dict)
        return record

    def list_reports(self, tenant_id: str, investigation_id: Optional[str] = None) -> List[ReportRecord]:
        col = report_repo.sync_collection
        if col is not None:
            q: Dict[str, Any] = {"tenant_id": tenant_id}
            if investigation_id:
                q["investigation_id"] = investigation_id
            try:
                docs = list(col.find(q, {"_id": 0}).sort("created_at", -1))
                if docs:
                    store = self._get_tenant_store(tenant_id)
                    for d in docs:
                        store[d["id"]] = ReportRecord(**d)
                    return [ReportRecord(**d) for d in docs]
            except Exception:
                pass

        store = self._get_tenant_store(tenant_id)
        results = list(store.values())
        if investigation_id:
            results = [r for r in results if r.investigation_id == investigation_id]
        results.sort(key=lambda x: x.created_at, reverse=True)
        return results

    def get_report(self, tenant_id: str, report_id: str) -> Optional[ReportRecord]:
        store = self._get_tenant_store(tenant_id)
        if report_id in store:
            return store[report_id]
        col = report_repo.sync_collection
        if col is not None:
            doc = col.find_one({"id": report_id, "tenant_id": tenant_id}, {"_id": 0})
            if doc:
                rec = ReportRecord(**doc)
                store[report_id] = rec
                return rec
        return None

report_service = ReportService()
